### ISSUE TITLE
Sub Accounts

### ISSUE THREAD

**Issue by ghost** [askmike/ftx-api-ws#1]
Is there a way to subscribe to two different subaccounts at once?

**Comment by askmike** [comment]
not on the same websocket, but this is an ftx restriction. You can easily create a socket for each account like so:

    const a = new FTXWs({
      key: 'x',
      secret: 'y',
      subaccount: 'z'
    })

    const b = new FTXWs({
      key: 'x',
      secret: 'y',
      subaccount: 'z'
    })

    const go = async () => {
      await a.connect();
      await b.connect();

      a.subscribe('fills');
      a.on('fills', console.log);

      b.subscribe('fills');
      b.on('fills', console.log);  
    }
